//console.log(document.getElementById ("titulonombre"))
//console.log(document.getElementById ("Apellido"))
//console.log(document.getElementById ("telefono"))
//console.log(document.getElementById ("correo"))
//console.log(document.getElementById ("input1"))
//console.log(document.getElementById ("label1"))
//console.log(document.getElementById ("label2"))
//console.log(document.getElementById ("label3"))
//console.log(document.getElementById ("label4"))
//console.log(document.getElementsByName("nombre"))
//console.log(document.getElementsByName("Apellido"))
//console.log(document.getElementsByName("telefono"))
//console.log(document.getElementsByName("correo"))
//console.log(document.getElementsByClassName("clase"))
console.log(document.getElementsByTagName("form"))
console.log(document.getElementsByTagName("label"))
console.log(document.getElementsByTagName("input"))
console.log(document.getElementsByTagName("script"))
console.log(document.getElementsByTagName("br"))